/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.deamec.telas;

import java.sql.*;
import br.com.deamec.dal.ModuloConexao;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.KeyEvent;
import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author danie
 */
public class TelaLogin extends javax.swing.JFrame {
    private Point point = new Point();

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public void logar() {
        //loga com os usuarios cadastrados do banco
        String sql = "select * from tbusuarios where login=? and senha=?";
        try {
            //As linhas abaixo usam a variavel pst, que pepara a consulta ao 
            // banco de dados em função do que foi digitado na caixas de textos.
            // O ? é substituido pelo conteudo das variaveis txtUsuario e Senha
            // e armazenha na variavel pst. Campo 1 e 2 são os campo usados.
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtUsuarioLogin.getText());
            pst.setString(2, txtSenha.getText());
            //A linha abaixo executa a query (consulta "select" ao banco)
            rs = pst.executeQuery();
            //Estrutura de decisão. Se existir usuario e senha correspondente
            if (rs.next()) {
                //A linha abaixo obtem o conteudo do campo perfil da tabela tbusuario
                String perfil = rs.getString(7);
                //System.out.println(privilegio);
                //A estrutura abaixo faz o tratamento do perfil do usuario
                if (perfil.equals("Administrador")) {
                    //TelaPrincipal (Classe), principal (objeto instanciado)
                    TelaPrincipal principal = new TelaPrincipal();
                    principal.setVisible(true);
                    TelaPrincipal.menRel.setEnabled(true);
                    TelaPrincipal.menCadUsu.setEnabled(true);
                    // mostra na lblusuarios tela principal, qual é o usuario do
                    // banco de dados que logou. rs
                    TelaPrincipal.lblUsuario.setText(rs.getString(2));
                    TelaPrincipal.lblUsuario.setForeground(Color.red);
                    this.dispose();
                    conexao.close();
                } else {
                    TelaPrincipal principal = new TelaPrincipal();
                    principal.setVisible(true);
                    TelaPrincipal.lblUsuario.setText(rs.getString(2));
                    this.dispose();

                }

            } else {
                 Point p = this.getLocation();
        TelaLogin loguinGui = this;
        new Thread() {
            @Override
            public void run() {
                try {
                    for (int i = 0; i < 6; i++) {
                        loguinGui.setLocation(p.x - 10, p.y);
                        sleep(20);
                        loguinGui.setLocation(p.x +10, p.y);
                        sleep(20);
                    }
                    loguinGui.setLocation(p.x, p.y);
                } catch (InterruptedException ex) {
                    Logger.getLogger(LoguinGui.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }.start();
                JOptionPane.showMessageDialog(null, "Usuário e/ou Senha inválido!");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        //chama o modulo de conexão criado em dal.
        conexao = ModuloConexao.conector();
        //A mesnagem que é colocada a baixo serve para saber o status da conexao.
        //System.out.println(conexao);
        //O comando abaixo é uma estrutura de decisão
        if (conexao != null) {
            //.setText mostra o texto na variavel preenchida ou nomeada
            lblStatus.setText("Conectado");
            //vamos usar icones. mostrar icones
            lblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/deamec/icones/dbstart.png")));
        } else {
            lblStatus.setText("Não Conectado");
            lblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/deamec/icones/dberror.png")));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuariologin = new javax.swing.JLabel();
        lblSenhaLogin = new javax.swing.JLabel();
        btnAcessarLogin = new javax.swing.JButton();
        btnSairLogin = new javax.swing.JButton();
        txtUsuarioLogin = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        lblStatus = new javax.swing.JLabel();
        lblFundoTelaLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(null);

        lblUsuariologin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUsuariologin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuariologin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/deamec/icones/loginicon.png"))); // NOI18N
        lblUsuariologin.setToolTipText("Usuário");
        getContentPane().add(lblUsuariologin);
        lblUsuariologin.setBounds(280, 190, 40, 30);

        lblSenhaLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSenhaLogin.setForeground(new java.awt.Color(255, 204, 0));
        lblSenhaLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSenhaLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/deamec/icones/senhaicon.png"))); // NOI18N
        lblSenhaLogin.setToolTipText("Senha");
        getContentPane().add(lblSenhaLogin);
        lblSenhaLogin.setBounds(280, 220, 40, 30);

        btnAcessarLogin.setText("Acessar");
        btnAcessarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcessarLoginActionPerformed(evt);
            }
        });
        btnAcessarLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAcessarLoginKeyPressed(evt);
            }
        });
        getContentPane().add(btnAcessarLogin);
        btnAcessarLogin.setBounds(280, 260, 100, 23);

        btnSairLogin.setText("Sair");
        btnSairLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnSairLogin);
        btnSairLogin.setBounds(380, 260, 100, 23);

        txtUsuarioLogin.setToolTipText("");
        txtUsuarioLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuarioLoginKeyPressed(evt);
            }
        });
        getContentPane().add(txtUsuarioLogin);
        txtUsuarioLogin.setBounds(320, 190, 160, 30);

        txtSenha.setToolTipText("");
        txtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenhaKeyPressed(evt);
            }
        });
        getContentPane().add(txtSenha);
        txtSenha.setBounds(320, 220, 160, 30);

        lblStatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/deamec/icones/dberror.png"))); // NOI18N
        getContentPane().add(lblStatus);
        lblStatus.setBounds(130, 250, 150, 40);

        lblFundoTelaLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/deamec/icones/fundo-telalogin2.jpg"))); // NOI18N
        getContentPane().add(lblFundoTelaLogin);
        lblFundoTelaLogin.setBounds(-10, -10, 510, 310);

        setSize(new java.awt.Dimension(489, 293));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairLoginActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairLoginActionPerformed

    private void btnAcessarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcessarLoginActionPerformed
        //Chamando o método logar
        logar();
        
    }//GEN-LAST:event_btnAcessarLoginActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
         point.x = evt.getX();
        point.y = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        Point p = this.getLocation();
        this.setLocation(p.x + evt.getX() - point.x, p.y + evt.getY() - point.y);
    }//GEN-LAST:event_formMouseDragged

    private void btnAcessarLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAcessarLoginKeyPressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_btnAcessarLoginKeyPressed

    private void txtUsuarioLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioLoginKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            logar();
        }
    }//GEN-LAST:event_txtUsuarioLoginKeyPressed

    private void txtSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            logar();
        }
    }//GEN-LAST:event_txtSenhaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcessarLogin;
    private javax.swing.JButton btnSairLogin;
    private javax.swing.JLabel lblFundoTelaLogin;
    private javax.swing.JLabel lblSenhaLogin;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblUsuariologin;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuarioLogin;
    // End of variables declaration//GEN-END:variables

    private static class LoguinGui {

        public LoguinGui() {
        }

        private void setLocation(int x, int y) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }
}
